In [1]:
import pandas as pd
import numpy as np
%matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from matplotlib.colors import ListedColormap
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
from pyspark import SparkContext

Using matplotlib backend: MacOSX


In [2]:
F = np.loadtxt('Matrice_Faillite_3ans.txt')
F

array([[2.50000000e+02, 3.91399994e+02],
       [3.18799988e+02, 4.73899994e+02],
       [7.20000000e+01, 2.53999996e+01],
       [7.20000000e+01, 2.86000004e+01],
       [4.50000000e+01, 2.31700001e+01],
       [1.50000000e+02, 9.50999985e+01],
       [1.25000000e+02, 3.12000008e+01],
       [1.31000000e+02, 7.30000000e+01],
       [3.00000000e+01, 9.34000015e+01],
       [3.00000000e+01, 1.46899994e+02],
       [3.20000000e+01, 3.35000000e+01],
       [1.00000000e+02, 1.57199997e+02],
       [1.00000000e+02, 1.34399994e+02],
       [1.00000000e+02, 8.98000031e+01],
       [5.00000000e+01, 0.00000000e+00],
       [5.00000000e+01, 0.00000000e+00],
       [4.00000000e+01, 9.25999985e+01],
       [4.00000000e+01, 1.33999996e+01],
       [2.50000000e+01, 4.75999985e+01],
       [2.50000000e+01, 1.01999998e+01],
       [6.00000000e+01, 4.09000015e+01],
       [1.00000000e+02, 1.09000000e+02],
       [5.00000000e+01, 1.36999998e+01],
       [7.50000000e+01, 1.73999996e+01],
       [2.160000

In [3]:
F2 = np.loadtxt('NF_BANQUES.txt')
F2

array([[2.5000e+02, 4.4260e+02],
       [2.5000e+02, 5.1180e+02],
       [2.5000e+02, 5.0560e+02],
       [2.5000e+02, 4.9850e+02],
       [2.5000e+02, 5.1040e+02],
       [2.5000e+02, 5.4310e+02],
       [2.5000e+02, 5.7130e+02],
       [2.5000e+02, 9.5570e+02],
       [2.5500e+02, 9.4110e+02],
       [2.5500e+02, 1.4650e+03],
       [2.5500e+02, 9.7290e+02],
       [4.0800e+02, 1.0366e+03],
       [4.0800e+02, 1.3145e+03],
       [4.0800e+02, 4.6378e+03],
       [4.0800e+02, 4.3286e+03],
       [4.0800e+02, 2.2559e+03],
       [4.0800e+02, 2.3158e+03],
       [4.0000e+02, 1.1305e+03],
       [4.0000e+02, 9.5880e+02],
       [4.0000e+02, 9.8860e+02],
       [4.0000e+02, 1.1454e+03],
       [5.0000e+02, 1.6404e+02],
       [5.0000e+02, 3.2220e+02],
       [5.0000e+02, 6.7380e+02],
       [5.0000e+02, 4.2820e+02],
       [5.0000e+02, 7.0140e+02],
       [5.0000e+02, 7.6220e+02],
       [5.0000e+02, 9.0580e+02],
       [5.0000e+02, 1.3371e+03],
       [5.0000e+02, 1.7635e+03],
       [5.

In [4]:
YF = np.loadtxt('MatriceY_Faillite_3ans.txt')
YF

array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1.

In [5]:
YF2=np.zeros((276, 1))
YF2

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [6]:
YF=np.reshape(YF,(276,1))
YF

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],

In [7]:
A=np.concatenate((F,F2))

In [8]:
B=np.concatenate((YF,YF2))

In [9]:
arrayF = np.append(A , B, axis = 1) #fusion des deux matrices
arrayF

array([[250.        , 391.3999939 ,   0.        ],
       [318.7999878 , 473.8999939 ,   1.        ],
       [ 72.        ,  25.39999962,   0.        ],
       ...,
       [105.        ,  60.9       ,   0.        ],
       [105.        ,  76.3       ,   0.        ],
       [105.        ,  63.8       ,   0.        ]])

In [10]:
dfF = pd.DataFrame(data=arrayF) 
dfF.columns =['cap', 'cash','output_F']
dfF

cap        cash  output_F
0    250.000000  391.399994       0.0
1    318.799988  473.899994       1.0
2     72.000000   25.400000       0.0
3     72.000000   28.600000       1.0
4     45.000000   23.170000       0.0
..          ...         ...       ...
547  100.000000   45.600000       0.0
548  100.000000   52.100000       0.0
549  105.000000   60.900000       0.0
550  105.000000   76.300000       0.0
551  105.000000   63.800000       0.0

[552 rows x 3 columns]

In [11]:
# Définir notre variable dépendante y et nos varaibles indépendantes X
X = dfF.iloc[:, [0, 1]].values #je prends cap et cash qui sont des variables dependantes
y = dfF.iloc[:, -1].values #je prends la derniere colonne de chaque ligne qui est une variable indépendante

In [12]:
# Diviser le dataset entre le Training set et le Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [13]:
# Construction du modèle
classifier = LogisticRegression() #
classifier.fit(X_train, y_train) #entrainement du modele

LogisticRegression()

In [14]:
# Faire de nouvelles prédictions
y_pred = classifier.predict(X_test) #faire des prédictions a partie de X_test
classifier.score(X_test,y_test) #taux de fiabilité(cohérence). cette ligne fait des predictions à X_test, ensuite compare ces resultats a Y_test

0.7142857142857143

In [15]:
#plt.plot(y_test,y_pred)

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7142857142857143

In [17]:
# Matrice de confusion

cm = confusion_matrix(y_test, y_pred) #on compare les resultats(y_test a y_pred)
print(cm)

#print(classification_report(y_test, y_pred))

#(0,0):nombre de res qui est 0 est le modele a predit que c'est 0
#(0,1):nombre de res qui est 1 est le modele a predit que c'est 0
#(1,0):nombre de res qui est 0 est le modele a predit que c'est 1
#(1,1):nombre de res qui est 1 est le modele a predit que c'est 1

[[40  1]
 [15  0]]


In [18]:
#2eme approche

import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [19]:
dfF

cap        cash  output_F
0    250.000000  391.399994       0.0
1    318.799988  473.899994       1.0
2     72.000000   25.400000       0.0
3     72.000000   28.600000       1.0
4     45.000000   23.170000       0.0
..          ...         ...       ...
547  100.000000   45.600000       0.0
548  100.000000   52.100000       0.0
549  105.000000   60.900000       0.0
550  105.000000   76.300000       0.0
551  105.000000   63.800000       0.0

[552 rows x 3 columns]

In [20]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
rfe = RFE(logreg, 20)
rfe = rfe.fit(X_train, y_train.ravel())
print(rfe.support_)
print(rfe.ranking_)

#L'élimination récursive des caractéristiques (RFE) repose 
#sur l'idée de construire un modèle de manière répétée et de
#choisir la caractéristique la plus performante ou la moins performante,
#de mettre cette caractéristique de côté et de répéter le processus avec 
#le reste des caractéristiques. Ce processus est appliqué jusqu'à ce que 
#toutes les caractéristiques de l'ensemble de données soient épuisées.



[ True  True]
[1 1]


/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=20 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [21]:
import statsmodels.api as sm
logit_model=sm.Logit(y_train,X_train)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.426052
         Iterations 10
                         Results: Logit
Model:              Logit            Pseudo R-squared: 0.239     
Dependent Variable: y                AIC:              426.6438  
Date:               2022-03-29 10:14 BIC:              435.0569  
No. Observations:   496              Log-Likelihood:   -211.32   
Df Model:           1                LL-Null:          -277.81   
Df Residuals:       494              LLR p-value:      9.1112e-31
Converged:          1.0000           Scale:            1.0000    
No. Iterations:     10.0000                                      
--------------------------------------------------------------------
       Coef.     Std.Err.       z       P>|z|      [0.025     0.975]
--------------------------------------------------------------------
x1    -0.0117      0.0033    -3.5294    0.0004    -0.0182    -0.0052
x2    -0.0086      0.0030    -2.8778    0.0040    -0.

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.52, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression()

In [23]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.74


In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[171  51]
 [ 24  42]]


In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.88      0.77      0.82       222
         1.0       0.45      0.64      0.53        66

    accuracy                           0.74       288
   macro avg       0.66      0.70      0.67       288
weighted avg       0.78      0.74      0.75       288



In [27]:
y_pred2 = logreg.predict(X_train)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.74


In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_train, y_pred2)
print(confusion_matrix)

[[152  40]
 [ 28  44]]


In [26]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
logit_roc_auc = roc_auc_score(y_test, logreg.predict(X_test))
fpr, tpr, thresholds = roc_curve(y_test, logreg.predict_proba(X_test)[:,1])
plt.figure()
plt.plot(fpr, tpr, label='Logistic Regression (area = %0.2f)' % logit_roc_auc)
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic')
plt.legend(loc="lower right")
plt.savefig('Log_ROC')
plt.show()

#La courbe ROC (receiver operating characteristic) est un autre 
#outil couramment utilisé avec les classifieurs binaires. 
#La ligne en pointillés représente la courbe ROC d'un classificateur
#purement aléatoire ; un bon classificateur se tient aussi loin que 
#possible de cette ligne (vers le coin supérieur gauche).

In [28]:
y_test.size

83

In [29]:
y_pred.size

83